### ISSUE TITLE
Initialization of pygame.display before call to show_picture

### ISSUE THREAD

**Issue by tonio213** [LoiX07/photobooth#1]
The remoteCtrl module runs fine, however I often got this traceback in stderr after I close the display:
```
Traceback (most recent call last):
  File "./remoteCtrl.py", line 205, in <module>
    exit(main())
  File "./remoteCtrl.py", line 198, in main
    slideshow.run()
  File "./remoteCtrl.py", line 107, in run
    self.display_next()
  File "./remoteCtrl.py", line 89, in display_next
    self.display.show_picture(filename)
  File "/home/tonio/code/photobooth/utils/gui.py", line 78, in show_picture
    image = pygame.transform.scale(image, new_size).convert()
pygame.error: cannot convert without pygame.display initialized
```
Maybe this is linked to the new multiprocess structure. It happens on branch feature/network but I didn't check (yet) on the other branches.

**Comment by LoiX07** [comment]
Added an explicit pygame display init
